version: '3.10'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - test_network

  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - test_network

volumes:
  db-data:

networks:
  test_network:
