"""add User model

Revision ID: 9cdc7b91404e
Revises: e9746e6b10f3
Create Date: 2024-04-16 13:59:33.894384

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9cdc7b91404e"
down_revision: Union[str, None] = "e9746e6b10f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "application",
        sa.Column("ads_url", sa.String(length=256), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("application", "ads_url")
    # ### end Alembic commands ###
